### ISSUE TITLE
Unable to complete Make on Ubuntu

### ISSUE THREAD

**Issue by sabun123** [jtsiomb/frapix#1]
Hi,
I'm trying to get Frapix setup on my Ubuntu 15.04 64bit machine. When I try to run `make` I get the following error:

``` bash
gcc -pedantic -Wall -fPIC -g   -c -o src/frapix.o src/frapix.c
src/frapix.c:37:20: fatal error: imago2.h: No such file or directory
 #include <imago2.h>
                    ^
compilation terminated.
<builtin>: recipe for target 'src/frapix.o' failed
make: *** [src/frapix.o] Error 1
```

I'm assuming this is a missing dependency that I need to install? What are the required libraries for building Frapix?

**Comment by sabun123** [comment]
Alright, I figured it out.
I need to grab libimago from here: https://code.google.com/p/libimago/source/checkout
After getting it on my desktop, I then needed libjpeg-dev to build libimago. Once I could `make` and `sudo make install` libimago, I was then able to run `make` and then `sudo make install` for frapix.

So, now I can get Frapix working with glxgears:
<a href="http://imgur.com/f5VLg1w"><img src="http://i.imgur.com/f5VLg1w.png" title="source: imgur.com" /></a>

It also works with Cities Skylines in Steam using:

``` bash
LD_PRELOAD=/usr/local/lib/libfrapix.so %command%
```

<a href="http://imgur.com/4XwmPe1"><img src="http://i.imgur.com/4XwmPe1.png" title="source: imgur.com" /></a>
<a href="http://imgur.com/gfLoRSO"><img src="http://i.imgur.com/gfLoRSO.png" title="source: imgur.com" /></a>

However, I cannot get Frapix to work with Wine. This is the main reason I installed Frapix. How do I get Frapix to work with Wine? Do I need a 32bit build of frapix for it to work with Wine? (since Wine is running as a 32bit prefix on my system)

P.S: It would help to add a **how-to install** and a **how-to run** quick guide either here on Github or in the README, for those of us who have never used it before. It would especially help the non-programmers. More importantly, if it's possible please ship Frapix with libimago.

Thank you for the great software :)

**Comment by jtsiomb** [comment]
Hello, I'm closing this issue, as it's not really a bug report. Feel
free to send me an email if you need help with compiling or running
something.

On Wed, Mar 25, 2015 at 02:23:43AM -0700, Yusuf Ismail Bin shukor wrote:

> However, I cannot get Frapix to work with Wine. This is the main
> reason I installed Frapix. How do I get Frapix to work with Wine? Do I
> need a 32bit build of frapix for it to work with Wine? (since Wine is
> running as a 32bit prefix on my system)

Certainly if you're running a 32bit program you need to compile frapix
as 32bit. You can achieve that by adding -m32 to both CFLAGS and LDFLAGS
in the Makefile.

If you encounter any other problems and you need help with this, again,
send me an email.

> P.S: It would help to add a **how-to install** and a **how-to run**
> quick guide either here on Github or in the README, for those of us
> who have never used it before.

Indeed, I should add something to the README file.

> More importantly, if it's possible please ship Frapix with libimago.

Absolutely not. They are two separate projects, but I should add
something about the libimago dependency in the frapix README file.

> Thank you for the great software :)

Cheers!
